python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_baseline --optimizer baseline --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --weight_decay 1e-3 --dropout --random_seed 1 --n_runs 3
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_imtl --optimizer imtl --dataset celeba --batch_size 128 --lr 0.0005 --decay_lr --num_epochs 50 --random_seed 1 --weight_decay 1e-3 --dropout --store_models --n_runs 3
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_mgda-ub_wdm4 --optimizer mgda-ub --dataset celeba --batch_size 128 --lr 0.0005 --decay_lr --weight_decay 1e-4 --dropout --num_epochs 50 --store_models --random_seed 1 --n_runs 3
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_graddrop_wdm4 --optimizer graddrop --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --weight_decay 1e-4 --dropout --random_seed 1 --n_runs 3
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_pcgrad --optimizer pcgrad --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --weight_decay 1e-3 --dropout --random_seed 2 --n_runs 1
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_rlw-dirichlet_wdm4 --optimizer rlw-dirichlet --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --random_seed 1 --weight_decay 1e-4 --dropout --store_models --n_runs 3
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_rlw-normal_wdm4 --optimizer rlw-normal --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --random_seed 1 --weight_decay 1e-4 --dropout --store_models --n_runs 3

python3.8 supervised_experiments/train_multi_task.py --label celeba_time_baseline --optimizer baseline --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 1 --store_models --weight_decay 1e-3 --dropout --random_seed 1 --n_runs 10 --time_measurement_exp
python3.8 supervised_experiments/train_multi_task.py --label celeba_time_imtl --optimizer imtl --dataset celeba --batch_size 128 --lr 0.0005 --decay_lr --num_epochs 1 --random_seed 1 --weight_decay 1e-3 --dropout --store_models --n_runs 10 --time_measurement_exp
python3.8 supervised_experiments/train_multi_task.py --label celeba_time_mgda-ub_reg --optimizer mgda-ub --dataset celeba --batch_size 128 --lr 0.0005 --decay_lr --dropout --num_epochs 1 --store_models --random_seed 1 --n_runs 10 --time_measurement_exp
python3.8 supervised_experiments/train_multi_task.py --label celeba_time_graddrop --optimizer graddrop --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 1 --store_models --weight_decay 1e-3 --dropout --random_seed 1 --n_runs 10 --time_measurement_exp
python3.8 supervised_experiments/train_multi_task.py --label celeba_time_pcgrad --optimizer pcgrad --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 1 --store_models --weight_decay 1e-3 --dropout --random_seed 1 --n_runs 10 --time_measurement_exp
python3.8 supervised_experiments/train_multi_task.py --label celeba_time_rlw-dirichlet --optimizer rlw-dirichlet --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 1 --store_models --weight_decay 1e-3 --dropout --random_seed 1 --n_runs 10 --time_measurement_exp
python3.8 supervised_experiments/train_multi_task.py --label celeba_time_rlw-normal --optimizer rlw-normal --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 1 --store_models --weight_decay 1e-3 --dropout --random_seed 1 --n_runs 10 --time_measurement_exp