python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_baseline_unreg --optimizer baseline --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --random_seed 1 --n_runs 3 --store_convergence_stats
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_imtl_unreg --optimizer imtl --dataset celeba --batch_size 128 --lr 0.0005 --decay_lr --num_epochs 50 --random_seed 1 --store_models --n_runs 3 --store_convergence_stats
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_mgda-ub_unreg --optimizer mgda-ub --dataset celeba --batch_size 128 --lr 0.0005 --decay_lr --num_epochs 50 --store_models --random_seed 1 --n_runs 3 --store_convergence_stats
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_graddrop_unreg --optimizer graddrop --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --random_seed 1 --n_runs 3 --store_convergence_stats
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_pcgrad_unreg --optimizer pcgrad --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --random_seed 2 --n_runs 1 --store_convergence_stats
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_rlw-dirichlet_unreg --optimizer rlw-dirichlet --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --random_seed 1 --n_runs 3 --store_convergence_stats
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_rlw-normal_unreg --optimizer rlw-normal --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --random_seed 1 --n_runs 3 --store_convergence_stats
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_baseline_nodrop_wdm4 --optimizer baseline --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --weight_decay 1e-4 --num_epochs 50 --store_models --random_seed 1 --n_runs 3
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_baseline_nodrop_wd2m3 --optimizer baseline --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --weight_decay 2e-3 --num_epochs 50 --store_models --random_seed 1 --n_runs 3
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_baseline_reg --optimizer baseline --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --weight_decay 1e-3 --dropout --random_seed 1 --n_runs 3

python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_baseline_noreg_morerep --optimizer baseline --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --random_seed 11 --n_runs 10
python3.8 supervised_experiments/train_multi_task.py --label celeba_testeval_baseline_morerep --optimizer baseline --dataset celeba --batch_size 128 --lr 0.001 --decay_lr --num_epochs 50 --store_models --weight_decay 1e-3 --dropout --random_seed 11 --n_runs 5